[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build --workspace=backend"

[deploy]
startCommand = "npm run start --workspace=backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
